- namespace: App\Dto\Repositories\ChatRepository
  class: AddChatDto
  properties:
    projectId: int
    messengerId: int
    messengerType: \App\Enums\MessengerTypeEnum
    status: \App\Enums\ChatStatusEnum

- namespace: App\Dto\Repositories\ChatRepository
  class: DeleteChatDto
  properties:
    projectId: int

- namespace: App\Dto\Repositories\ChatRepository
  class: GetChatByIdDto
  properties:
    projectId: int
    id: int

- namespace: App\Dto\Repositories\ChatRepository
  class: GetChatByProjectIdDto
  properties:
    projectId: int

- namespace: App\Dto\Repositories\ChatRepository
  class: ChatDto
  properties:
    projectId: int
    id: int
    messengerId: int
    messengerType: \App\Enums\MessengerTypeEnum
    status: \App\Enums\ChatStatusEnum
