- namespace: App\Dto\Repositories\CredentialRepository
  class: AddCredentialDto
  properties:
    projectId: int
    token: string
    dateExpired: string

- namespace: App\Dto\Repositories\CredentialRepository
  class: DeleteCredentialDto
  properties:
    projectId: int

- namespace: App\Dto\Repositories\CredentialRepository
  class: GetCredentialByProjectIdDto
  properties:
    projectId: int

- namespace: App\Dto\Repositories\CredentialRepository
  class: CredentialDto
  properties:
    id: int
    projectId: int
    token: string
    dateExpired: string
    isRequestWorkable: bool
