- namespace: App\Dto\Repositories\ProjectRepository
  class: DeleteProjectDto
  properties:
    adminId: int
    id: int

- namespace: App\Dto\Repositories\ProjectRepository
  class: AddProjectDto
  properties:
    adminId: int
    name: string
    gitRepositoryUrl: string
    gitType: \App\Enums\GitServiceTypeEnum
    reviewType: \App\Enums\ReviewTypeEnum

- namespace: App\Dto\Repositories\ProjectRepository
  class: ChangeProjectReviewTypeDto
  properties:
    adminId: int
    id: int
    reviewType: \App\Enums\ReviewTypeEnum

- namespace: App\Dto\Repositories\ProjectRepository
  class: ProjectDto
  properties:
    id: int
    adminId: int
    name: string
    gitRepositoryUrl: string
    gitType: \App\Enums\GitServiceTypeEnum
    reviewType: \App\Enums\ReviewTypeEnum

- namespace: App\Dto\Repositories\ProjectRepository
  class: GetProjectListDto
  properties:
    adminId: int

- namespace: App\Dto\Repositories\ProjectRepository
  class: GetProjectDto
  properties:
    id: int

- namespace: App\Dto\Repositories\ProjectRepository
  class: GetProjectByNameDto
  properties:
    adminId: int
    name: string

- namespace: App\Dto\Repositories\ProjectRepository
  class: GetProjectByGitRepositoryUrlDto
  properties:
    adminId: int
    gitRepositoryUrl: string
