- namespace: App\Dto\Services\CredentialService
  class: AddCredentialDto
  properties:
    projectId: int
    token: string
    dateExpired: \Datetime

- namespace: App\Dto\Services\CredentialService
  class: DeleteCredentialDto
  properties:
    projectId: int

- namespace: App\Dto\Services\CredentialService
  class: GetCredentialByProjectIdDto
  properties:
    projectId: int

- namespace: App\Dto\Services\CredentialService
  class: CredentialDto
  properties:
    id: int
    projectId: int
    token: string
    dateExpired: \Datetime
    isRequestWorkable: bool
