- namespace: App\Dto\UseCase\Credentials
  class: AddCredentialDto
  properties:
    telegramUserId: int
    projectId: int
    token: string
    dateExpired: string

- namespace: App\Dto\UseCase\Credentials
  class: CredentialDto
  properties:
    id: int
    projectId: int
    token: string
    dateExpired: string
    isRequestWorkable: bool
