services:
  App:
    resource: /src
    exclude: /src/Application.php

  Eva\HttpKernel\EventListeners:
    resource: /vendor/eva/http-kernel/src/EventListeners

  Eva\Console\EventListeners:
    resource: /vendor/eva/console/src/EventListeners

  Eva\ApiDoc:
    resource: /vendor/eva/api-doc/src

  Eva\Console\Commands:
    resource: /vendor/eva/console/src/Commands

  Eva\Database\Migrations:
    resource: /vendor/eva/database/src/Migrations

  Eva\Http\ClientInterface:
    class: Eva\Http\Client

  Eva\Database\ConnectionStoreInterface:
    class: Eva\Database\ConnectionStore

  Eva\Console\RouterInterface:
    class: Eva\Console\Router
    calls:
      - setRoutes: '%package.console%'

  Eva\HttpKernel\RouterInterface:
    class: Eva\HttpKernel\Router
    calls:
      - setRoutes: '%package.routes%'

  App\Infrastructure\TelegramRouter:
    class: App\Infrastructure\TelegramRouter
    calls:
      - setRoutes: '%package.telegram_routes%'

  Eva\Console\Commands\ListCommand:
    arguments:
      commands: '%package.console%'

  Eva\Database\Migrations\Migrator:
    arguments:
      config: '%package.schema%'

  App\Handler\TelegramUpdateHandler:
    arguments:
      botNickname: '%env.TELEGRAM_NICKNAME%'

  App\Services\RequestServices\MainServiceRequestService:
    arguments:
      host: '%env.MAIN_SERVICE_HOST%'

  App\Services\RequestServices\TelegramRequestService:
    arguments:
      token: '%env.TELEGRAM_API_TOKEN%'
      host: '%env.REQUEST_SENDER_SERVICE_HOST%'

  App\Services\RequestServices\FluentdRequestService:
    arguments:
      host: '%env.REQUEST_SENDER_SERVICE_HOST%'
      tag: '%env.FLUENTD_TAG%'

  Psr\Log\LoggerInterface:
    class: App\Logger\FluentdLogger

  Eva\DtoCreator\DtoCreatorCommand:
    class: Eva\DtoCreator\DtoCreatorCommand

service_providers:
  - Eva\EventDispatcher\EventDispatcherProvider
  - App\ServiceProviders\DatabaseConnectionServiceProvider
