list: Eva\Console\Commands\ListCommand

app.validation.schema.creator: App\Commands\CreateValidationSchemaCommand
app.dto.creator: Eva\DtoCreator\DtoCreatorCommand

db.migrations.create: Eva\Database\Migrations\Commands\CreateCommand
db.migrations.migrate: Eva\Database\Migrations\Commands\MigrateCommand
db.migrations.rollback: Eva\Database\Migrations\Commands\RollbackCommand
db.migrations.status: Eva\Database\Migrations\Commands\StatusCommand
