- namespace: App\Dto\Services\CredentialsService
  class: AddCredentialDto
  properties:
    adminId: int
    projectId: int
    token: string
    dateExpired: string

- namespace: App\Dto\Services\CredentialsService
  class: CredentialDto
  properties:
    id: int
    projectId: int
    token: string
    dateExpired: string
    isRequestWorkable: bool
